import { afterEach, describe, expect, it, vi } from "vitest";
import { StructuredOutputError } from "@ai-hero/sandcastle";

import {
  createSandcastlePlannerSession,
} from "../.sandcastle/planner-session.js";
import { plannerOutputSchema } from "../.sandcastle/planner.js";
import { STRUCTURED_EXTRACTION_ATTEMPTS } from "../.sandcastle/same-session-structured-extraction.js";

const output = {
  status: "ready" as const,
  implementationSummary: "Implement the requested behavior.",
  blockingReason: null,
  allowsAutomationChanges: false,
  issue: {
    number: 101,
    title: "Planner",
    body: "Plan this Issue.",
    labels: ["Sandcastle"],
    comments: [],
  },
};

describe("Sandcastle Planner session adapter", () => {
  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("retains the complete raw Agent stream in the inherited whole-job log", async () => {
    vi.stubEnv("SANDCASTLE_JOB_STDOUT_LOG", "/trusted/jobs/logs/job-101/stdout.log");
    const runAgent = vi.fn().mockResolvedValue({ output });
    const session = createSandcastlePlannerSession({
      sandbox: { kind: "fake-sandbox" } as never,
      hooks: {},
      runAgent: runAgent as never,
      createAgent: vi.fn().mockReturnValue({ name: "fake-agent" }) as never,
    });

    await session.run({
      issueNumber: 101,
      model: "planner-model",
      output: { tag: "plan", schema: plannerOutputSchema },
    });

    expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({
      logging: {
        type: "file",
        path: "/trusted/jobs/logs/job-101/stdout.log",
        verbose: true,
      },
    }));
  });

  it("runs a fresh read-only Planner session with structured output", async () => {
    const runAgent = vi.fn().mockResolvedValue({ output });
    const createAgent = vi.fn().mockReturnValue({ name: "fake-agent" });
    const sandbox = { kind: "fake-sandbox" };
    const hooks = { sandbox: { onSandboxReady: [] } };
    const session = createSandcastlePlannerSession({
      sandbox: sandbox as never,
      hooks,
      runAgent: runAgent as never,
      createAgent: createAgent as never,
    });

    await expect(session.run({
      issueNumber: 101,
      model: "planner-model",
      output: { tag: "plan", schema: plannerOutputSchema },
    })).resolves.toEqual(output);

    expect(runAgent).toHaveBeenCalledOnce();
    expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({
      sandbox,
      hooks,
      branchStrategy: { type: "head" },
      maxIterations: 1,
      name: "planner-issue-101",
      output: expect.objectContaining({ tag: "plan" }),
    }));
    const request = runAgent.mock.calls[0]![0];
    expect(createAgent).toHaveBeenCalledWith("planner-model");
    expect(request.agent).toEqual({ name: "fake-agent" });
    expect(request.prompt).toContain("gh issue view 101 --comments");
    expect(request.prompt).toContain("body, labels, and all comments");
    expect(request.prompt).toContain("<plan>");
    expect(request.prompt).toContain("exactly match this strict schema");
    expect(request.prompt).toContain("implementationSummary (a non-empty string, never an array or object)");
    expect(request.prompt).toContain("include no fields other than those listed");
    expect(request.prompt).toContain("Do not add scope, metadata, explanation, helper, or any other fields");
    expect(request.prompt).toContain(
      "Determine whether the Issue explicitly permits changes to Sandcastle or GitHub automation configuration",
    );
    expect(request.prompt).toContain(
      "Treat comments generated by prior Automation failures (for example, comments saying an Automation operation is blocked and naming a local job) as execution history only: preserve them in the returned issue context, but they must not by themselves make the plan blocked. Base blocking decisions on the Issue's requested work, current state, dependencies, and unresolved human decisions.",
    );
    expect(request.prompt).not.toContain(output.issue.body);
    expect(request.prompt).not.toContain("shared accumulating branch");
    expect(request.prompt).not.toContain("git fetch origin");
  });

  it("arms the shared parse-retry budget so a malformed <plan> is retried in-session", async () => {
    const runAgent = vi.fn().mockResolvedValue({ output });
    const session = createSandcastlePlannerSession({
      sandbox: { kind: "fake-sandbox" } as never,
      hooks: {},
      runAgent: runAgent as never,
      createAgent: vi.fn().mockReturnValue({ name: "fake-agent" }) as never,
    });

    await expect(session.run({
      issueNumber: 101,
      model: "planner-model",
      output: { tag: "plan", schema: plannerOutputSchema },
    })).resolves.toEqual(output);

    // The library resumes the failed session with the parse detail and the
    // model re-emits a corrected <plan>; the session layer only wires the
    // budget derived from the shared constant.
    expect(runAgent).toHaveBeenCalledWith(expect.objectContaining({
      output: expect.objectContaining({
        tag: "plan",
        maxRetries: STRUCTURED_EXTRACTION_ATTEMPTS - 1,
      }),
    }));
  });

  it("propagates the StructuredOutputError when the parse-retry budget is exhausted", async () => {
    const exhausted = new StructuredOutputError("Structured output tag <plan> contains invalid JSON", {
      tag: "plan",
      rawMatched: "not JSON",
      commits: [],
      branch: "sandcastle/spec-437",
      sessionId: "session-1",
    });
    const runAgent = vi.fn().mockRejectedValue(exhausted);
    const session = createSandcastlePlannerSession({
      sandbox: { kind: "fake-sandbox" } as never,
      hooks: {},
      runAgent: runAgent as never,
      createAgent: vi.fn().mockReturnValue({ name: "fake-agent" }) as never,
    });

    // The failure surfaces unchanged (not swallowed, not converted) so the
    // operation fails as Blocked Automation in bounded time.
    await expect(session.run({
      issueNumber: 101,
      model: "planner-model",
      output: { tag: "plan", schema: plannerOutputSchema },
    })).rejects.toBe(exhausted);
  });

  it("runs a fresh read-only Planner session with Spec child context", async () => {
    const runAgent = vi.fn().mockResolvedValue({ output });
    const createAgent = vi.fn().mockReturnValue({ name: "fake-agent" });
    const sandbox = { kind: "fake-sandbox" };
    const hooks = { sandbox: { onSandboxReady: [] } };
    const session = createSandcastlePlannerSession({
      sandbox: sandbox as never,
      hooks,
      runAgent: runAgent as never,
      createAgent: createAgent as never,
      specContext: { parentSpec: 306, branch: "sandcastle/spec-306" },
    });

    await expect(session.run({
      issueNumber: 309,
      model: "planner-model",
      output: { tag: "plan", schema: plannerOutputSchema },
    })).resolves.toEqual(output);

    const request = runAgent.mock.calls[0]![0];
    expect(request.prompt).toContain(
      "This Issue is one child of Spec #306, delivered on the shared accumulating branch sandcastle/spec-306",
    );
    expect(request.prompt).toContain(
      "If sandcastle/spec-306 already exists on origin, inspect the accumulated branch state with git fetch origin sandcastle/spec-306",
    );
    expect(request.prompt).toContain(
      "git show origin/sandcastle/spec-306:<path>",
    );
    expect(request.prompt).toContain(
      "Plan against the accumulated branch state when it exists, not the bare base checkout",
    );
  });
});
